# Generated by Django 5.0 on 2023-12-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helloworld", "0002_post_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(),
        ),
    ]
